services:
  web:
    build: .
    container_name: viagem_uloha_container
    ports:
      - "8080:80"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: viagem
      DATA_DIR: /data/db
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./data/db:/data/db

  mongo:
    image: mongo:8
    container_name: viagem_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  mongo_data:
